### ISSUE TITLE
Thoughts on swagger configuration

### ISSUE THREAD

**Issue by nicolaiarocci** [nicolaiarocci/eve-swagger#1]
There is a lot of info that is not available in Eve and yet is needed for Swagger. The current approach is that the settings can be expanded with a `SWAGGER` document which includes all the extra data. I am not sure this is the best approach. 

Maybe we could just add support new keywords in the settings file, eventually prepended by the `SWAGGER` title, very much like the `MONGO` prefix( e.g. `API_TITLE` or `SWAGGER_API_TITLE`). This would also come in handy at a later stage, when we're working on resources ("paths" in swagger terms). Iterating through the  `DOMAIN` would allow to retrieve both eve standard settings *and* swagger's if available, instead of having to look at two different places during the whole process. Would probably be easier on the user too, as all resource configuration is held at one place.

**Comment by cyppan** [comment]
+1 for the `SWAGGER_` prefixed approach in the already existing domain dictionaries.
