### ISSUE TITLE
ImportError: No module named 'swagger'

### ISSUE THREAD

**Issue by clovis818** [nicolaiarocci/eve-swagger#4]
pip install eve-swagger
Collecting eve-swagger
  Using cached Eve-Swagger-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lzr7ya90/eve-swagger/setup.py", line 7, in <module>
        VERSION = __import__('eve_swagger').__version__
      File "/tmp/pip-build-lzr7ya90/eve-swagger/eve_swagger/__init__.py", line 10, in <module>
        from swagger import swagger  # noqa
    ImportError: No module named 'swagger'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lzr7ya90/eve-swagger/

**Comment by nicolaiarocci** [comment]
Is Eve (and Flask) installed in your virtualenv? There's something odd going on with `install_requires` in setup.py.

**Comment by nicolaiarocci** [comment]
Should be fixed with 0.0.3 which is now on PyPI. Thanks.
